name: CI Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.12.7'
      
      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy
      
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -P data_file=heart_preprocessed.csv --env-manager=local